#!/bin/csh
#$ -M zhu4@nd.edu     # Email address for job notification
#$ -m abe               # Send mail when job begins, ends and aborts
#$ -q gpu             
#$ -l gpu_card=1
#$ -N deepritz

module load python

python mainHeat.py train --model='ResNet' --functional='heat' --pretrain='heatfix.pt' --grid='heatgrid.pt' --exact='heatexact.pt' --num_node=10 --max_epoch=100 --step_size=200 --lr=1e-2
